# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-12 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20171212_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(default='Dec 12 2017 10 43 17'),
        ),
    ]
