# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-12 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20171212_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default='Dec 12 2017 10 49 50'),
        ),
    ]
